M48
; DRILL file {KiCad 9.0.0} date 2025-05-12T22:41:29+0200
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2025-05-12T22:41:29+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.0
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C1.150
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C1.650
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C2.500
%
G90
G05
T1
X164.25Y-83.888
T2
X185.25Y-83.888
T3
X115.0Y-54.0
X115.0Y-103.0
X194.207Y-54.0
X194.25Y-103.5
M30
